// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileUpload.proto

package generatedClasses;

public final class FileUpload {
  private FileUpload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileUploadRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.FileUploadRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    int getStaffId();

    /**
     * <code>string file_path = 2;</code>
     * @return The filePath.
     */
    java.lang.String getFilePath();
    /**
     * <code>string file_path = 2;</code>
     * @return The bytes for filePath.
     */
    com.google.protobuf.ByteString
        getFilePathBytes();
  }
  /**
   * Protobuf type {@code proto.FileUploadRequest}
   */
  public static final class FileUploadRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.FileUploadRequest)
      FileUploadRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileUploadRequest.newBuilder() to construct.
    private FileUploadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileUploadRequest() {
      filePath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileUploadRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileUploadRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              staffId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              filePath_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedClasses.FileUpload.internal_static_proto_FileUploadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedClasses.FileUpload.internal_static_proto_FileUploadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedClasses.FileUpload.FileUploadRequest.class, generatedClasses.FileUpload.FileUploadRequest.Builder.class);
    }

    public static final int STAFF_ID_FIELD_NUMBER = 1;
    private int staffId_;
    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    @java.lang.Override
    public int getStaffId() {
      return staffId_;
    }

    public static final int FILE_PATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object filePath_;
    /**
     * <code>string file_path = 2;</code>
     * @return The filePath.
     */
    @java.lang.Override
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filePath_ = s;
        return s;
      }
    }
    /**
     * <code>string file_path = 2;</code>
     * @return The bytes for filePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (staffId_ != 0) {
        output.writeInt32(1, staffId_);
      }
      if (!getFilePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filePath_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (staffId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, staffId_);
      }
      if (!getFilePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filePath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generatedClasses.FileUpload.FileUploadRequest)) {
        return super.equals(obj);
      }
      generatedClasses.FileUpload.FileUploadRequest other = (generatedClasses.FileUpload.FileUploadRequest) obj;

      if (getStaffId()
          != other.getStaffId()) return false;
      if (!getFilePath()
          .equals(other.getFilePath())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STAFF_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStaffId();
      hash = (37 * hash) + FILE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getFilePath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.FileUpload.FileUploadRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generatedClasses.FileUpload.FileUploadRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.FileUploadRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.FileUploadRequest)
        generatedClasses.FileUpload.FileUploadRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedClasses.FileUpload.internal_static_proto_FileUploadRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedClasses.FileUpload.internal_static_proto_FileUploadRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedClasses.FileUpload.FileUploadRequest.class, generatedClasses.FileUpload.FileUploadRequest.Builder.class);
      }

      // Construct using generatedClasses.FileUpload.FileUploadRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        staffId_ = 0;

        filePath_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedClasses.FileUpload.internal_static_proto_FileUploadRequest_descriptor;
      }

      @java.lang.Override
      public generatedClasses.FileUpload.FileUploadRequest getDefaultInstanceForType() {
        return generatedClasses.FileUpload.FileUploadRequest.getDefaultInstance();
      }

      @java.lang.Override
      public generatedClasses.FileUpload.FileUploadRequest build() {
        generatedClasses.FileUpload.FileUploadRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generatedClasses.FileUpload.FileUploadRequest buildPartial() {
        generatedClasses.FileUpload.FileUploadRequest result = new generatedClasses.FileUpload.FileUploadRequest(this);
        result.staffId_ = staffId_;
        result.filePath_ = filePath_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedClasses.FileUpload.FileUploadRequest) {
          return mergeFrom((generatedClasses.FileUpload.FileUploadRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedClasses.FileUpload.FileUploadRequest other) {
        if (other == generatedClasses.FileUpload.FileUploadRequest.getDefaultInstance()) return this;
        if (other.getStaffId() != 0) {
          setStaffId(other.getStaffId());
        }
        if (!other.getFilePath().isEmpty()) {
          filePath_ = other.filePath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generatedClasses.FileUpload.FileUploadRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generatedClasses.FileUpload.FileUploadRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int staffId_ ;
      /**
       * <code>int32 staff_id = 1;</code>
       * @return The staffId.
       */
      @java.lang.Override
      public int getStaffId() {
        return staffId_;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @param value The staffId to set.
       * @return This builder for chaining.
       */
      public Builder setStaffId(int value) {
        
        staffId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStaffId() {
        
        staffId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object filePath_ = "";
      /**
       * <code>string file_path = 2;</code>
       * @return The filePath.
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string file_path = 2;</code>
       * @return The bytes for filePath.
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_path = 2;</code>
       * @param value The filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_path = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilePath() {
        
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>string file_path = 2;</code>
       * @param value The bytes for filePath to set.
       * @return This builder for chaining.
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filePath_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.FileUploadRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.FileUploadRequest)
    private static final generatedClasses.FileUpload.FileUploadRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generatedClasses.FileUpload.FileUploadRequest();
    }

    public static generatedClasses.FileUpload.FileUploadRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileUploadRequest>
        PARSER = new com.google.protobuf.AbstractParser<FileUploadRequest>() {
      @java.lang.Override
      public FileUploadRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileUploadRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileUploadRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileUploadRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generatedClasses.FileUpload.FileUploadRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileUploadResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.FileUploadResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string file_name = 1;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string file_name = 1;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>string upload_status = 2;</code>
     * @return The uploadStatus.
     */
    java.lang.String getUploadStatus();
    /**
     * <code>string upload_status = 2;</code>
     * @return The bytes for uploadStatus.
     */
    com.google.protobuf.ByteString
        getUploadStatusBytes();
  }
  /**
   * Protobuf type {@code proto.FileUploadResponse}
   */
  public static final class FileUploadResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.FileUploadResponse)
      FileUploadResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileUploadResponse.newBuilder() to construct.
    private FileUploadResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileUploadResponse() {
      fileName_ = "";
      uploadStatus_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileUploadResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileUploadResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uploadStatus_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedClasses.FileUpload.internal_static_proto_FileUploadResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedClasses.FileUpload.internal_static_proto_FileUploadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedClasses.FileUpload.FileUploadResponse.class, generatedClasses.FileUpload.FileUploadResponse.Builder.class);
    }

    public static final int FILE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fileName_;
    /**
     * <code>string file_name = 1;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string file_name = 1;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPLOAD_STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object uploadStatus_;
    /**
     * <code>string upload_status = 2;</code>
     * @return The uploadStatus.
     */
    @java.lang.Override
    public java.lang.String getUploadStatus() {
      java.lang.Object ref = uploadStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uploadStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string upload_status = 2;</code>
     * @return The bytes for uploadStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUploadStatusBytes() {
      java.lang.Object ref = uploadStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uploadStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
      }
      if (!getUploadStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uploadStatus_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
      }
      if (!getUploadStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uploadStatus_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generatedClasses.FileUpload.FileUploadResponse)) {
        return super.equals(obj);
      }
      generatedClasses.FileUpload.FileUploadResponse other = (generatedClasses.FileUpload.FileUploadResponse) obj;

      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getUploadStatus()
          .equals(other.getUploadStatus())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (37 * hash) + UPLOAD_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getUploadStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.FileUpload.FileUploadResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generatedClasses.FileUpload.FileUploadResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.FileUploadResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.FileUploadResponse)
        generatedClasses.FileUpload.FileUploadResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedClasses.FileUpload.internal_static_proto_FileUploadResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedClasses.FileUpload.internal_static_proto_FileUploadResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedClasses.FileUpload.FileUploadResponse.class, generatedClasses.FileUpload.FileUploadResponse.Builder.class);
      }

      // Construct using generatedClasses.FileUpload.FileUploadResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fileName_ = "";

        uploadStatus_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedClasses.FileUpload.internal_static_proto_FileUploadResponse_descriptor;
      }

      @java.lang.Override
      public generatedClasses.FileUpload.FileUploadResponse getDefaultInstanceForType() {
        return generatedClasses.FileUpload.FileUploadResponse.getDefaultInstance();
      }

      @java.lang.Override
      public generatedClasses.FileUpload.FileUploadResponse build() {
        generatedClasses.FileUpload.FileUploadResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generatedClasses.FileUpload.FileUploadResponse buildPartial() {
        generatedClasses.FileUpload.FileUploadResponse result = new generatedClasses.FileUpload.FileUploadResponse(this);
        result.fileName_ = fileName_;
        result.uploadStatus_ = uploadStatus_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedClasses.FileUpload.FileUploadResponse) {
          return mergeFrom((generatedClasses.FileUpload.FileUploadResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedClasses.FileUpload.FileUploadResponse other) {
        if (other == generatedClasses.FileUpload.FileUploadResponse.getDefaultInstance()) return this;
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        if (!other.getUploadStatus().isEmpty()) {
          uploadStatus_ = other.uploadStatus_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generatedClasses.FileUpload.FileUploadResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generatedClasses.FileUpload.FileUploadResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string file_name = 1;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string file_name = 1;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_name = 1;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 1;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uploadStatus_ = "";
      /**
       * <code>string upload_status = 2;</code>
       * @return The uploadStatus.
       */
      public java.lang.String getUploadStatus() {
        java.lang.Object ref = uploadStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uploadStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string upload_status = 2;</code>
       * @return The bytes for uploadStatus.
       */
      public com.google.protobuf.ByteString
          getUploadStatusBytes() {
        java.lang.Object ref = uploadStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uploadStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string upload_status = 2;</code>
       * @param value The uploadStatus to set.
       * @return This builder for chaining.
       */
      public Builder setUploadStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uploadStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string upload_status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUploadStatus() {
        
        uploadStatus_ = getDefaultInstance().getUploadStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string upload_status = 2;</code>
       * @param value The bytes for uploadStatus to set.
       * @return This builder for chaining.
       */
      public Builder setUploadStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uploadStatus_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.FileUploadResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.FileUploadResponse)
    private static final generatedClasses.FileUpload.FileUploadResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generatedClasses.FileUpload.FileUploadResponse();
    }

    public static generatedClasses.FileUpload.FileUploadResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileUploadResponse>
        PARSER = new com.google.protobuf.AbstractParser<FileUploadResponse>() {
      @java.lang.Override
      public FileUploadResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileUploadResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileUploadResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileUploadResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generatedClasses.FileUpload.FileUploadResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FileUploadRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FileUploadRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FileUploadResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_FileUploadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020FileUpload.proto\022\005proto\"8\n\021FileUploadR" +
      "equest\022\020\n\010staff_id\030\001 \001(\005\022\021\n\tfile_path\030\002 " +
      "\001(\t\">\n\022FileUploadResponse\022\021\n\tfile_name\030\001" +
      " \001(\t\022\025\n\rupload_status\030\002 \001(\t2\232\001\n\021FileUplo" +
      "adService\022A\n\nuploadFile\022\030.proto.FileUplo" +
      "adRequest\032\031.proto.FileUploadResponse\022B\n\013" +
      "uploadImage\022\030.proto.FileUploadRequest\032\031." +
      "proto.FileUploadResponseB\022\n\020generatedCla" +
      "ssesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_FileUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_FileUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FileUploadRequest_descriptor,
        new java.lang.String[] { "StaffId", "FilePath", });
    internal_static_proto_FileUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_FileUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_FileUploadResponse_descriptor,
        new java.lang.String[] { "FileName", "UploadStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
