// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StaffRequest.proto

// Protobuf Java Version: 3.25.1
package generatedClasses;

public final class StaffRequestOuterClass {
  private StaffRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StaffRequest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.StaffRequest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    int getStaffId();
  }
  /**
   * Protobuf type {@code proto.StaffRequest1}
   */
  public static final class StaffRequest1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.StaffRequest1)
      StaffRequest1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StaffRequest1.newBuilder() to construct.
    private StaffRequest1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StaffRequest1() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StaffRequest1();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest1_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedClasses.StaffRequestOuterClass.StaffRequest1.class, generatedClasses.StaffRequestOuterClass.StaffRequest1.Builder.class);
    }

    public static final int STAFF_ID_FIELD_NUMBER = 1;
    private int staffId_ = 0;
    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    @java.lang.Override
    public int getStaffId() {
      return staffId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (staffId_ != 0) {
        output.writeInt32(1, staffId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (staffId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, staffId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generatedClasses.StaffRequestOuterClass.StaffRequest1)) {
        return super.equals(obj);
      }
      generatedClasses.StaffRequestOuterClass.StaffRequest1 other = (generatedClasses.StaffRequestOuterClass.StaffRequest1) obj;

      if (getStaffId()
          != other.getStaffId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STAFF_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStaffId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generatedClasses.StaffRequestOuterClass.StaffRequest1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.StaffRequest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.StaffRequest1)
        generatedClasses.StaffRequestOuterClass.StaffRequest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedClasses.StaffRequestOuterClass.StaffRequest1.class, generatedClasses.StaffRequestOuterClass.StaffRequest1.Builder.class);
      }

      // Construct using generatedClasses.StaffRequestOuterClass.StaffRequest1.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        staffId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest1_descriptor;
      }

      @java.lang.Override
      public generatedClasses.StaffRequestOuterClass.StaffRequest1 getDefaultInstanceForType() {
        return generatedClasses.StaffRequestOuterClass.StaffRequest1.getDefaultInstance();
      }

      @java.lang.Override
      public generatedClasses.StaffRequestOuterClass.StaffRequest1 build() {
        generatedClasses.StaffRequestOuterClass.StaffRequest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generatedClasses.StaffRequestOuterClass.StaffRequest1 buildPartial() {
        generatedClasses.StaffRequestOuterClass.StaffRequest1 result = new generatedClasses.StaffRequestOuterClass.StaffRequest1(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(generatedClasses.StaffRequestOuterClass.StaffRequest1 result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.staffId_ = staffId_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedClasses.StaffRequestOuterClass.StaffRequest1) {
          return mergeFrom((generatedClasses.StaffRequestOuterClass.StaffRequest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedClasses.StaffRequestOuterClass.StaffRequest1 other) {
        if (other == generatedClasses.StaffRequestOuterClass.StaffRequest1.getDefaultInstance()) return this;
        if (other.getStaffId() != 0) {
          setStaffId(other.getStaffId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                staffId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int staffId_ ;
      /**
       * <code>int32 staff_id = 1;</code>
       * @return The staffId.
       */
      @java.lang.Override
      public int getStaffId() {
        return staffId_;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @param value The staffId to set.
       * @return This builder for chaining.
       */
      public Builder setStaffId(int value) {

        staffId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStaffId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        staffId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.StaffRequest1)
    }

    // @@protoc_insertion_point(class_scope:proto.StaffRequest1)
    private static final generatedClasses.StaffRequestOuterClass.StaffRequest1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generatedClasses.StaffRequestOuterClass.StaffRequest1();
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StaffRequest1>
        PARSER = new com.google.protobuf.AbstractParser<StaffRequest1>() {
      @java.lang.Override
      public StaffRequest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StaffRequest1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StaffRequest1> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generatedClasses.StaffRequestOuterClass.StaffRequest1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StaffRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.StaffRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Staff staff = 1;</code>
     * @return Whether the staff field is set.
     */
    boolean hasStaff();
    /**
     * <code>.proto.Staff staff = 1;</code>
     * @return The staff.
     */
    generatedClasses.StaffOuterClass.Staff getStaff();
    /**
     * <code>.proto.Staff staff = 1;</code>
     */
    generatedClasses.StaffOuterClass.StaffOrBuilder getStaffOrBuilder();
  }
  /**
   * Protobuf type {@code proto.StaffRequest}
   */
  public static final class StaffRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.StaffRequest)
      StaffRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StaffRequest.newBuilder() to construct.
    private StaffRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StaffRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StaffRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedClasses.StaffRequestOuterClass.StaffRequest.class, generatedClasses.StaffRequestOuterClass.StaffRequest.Builder.class);
    }

    private int bitField0_;
    public static final int STAFF_FIELD_NUMBER = 1;
    private generatedClasses.StaffOuterClass.Staff staff_;
    /**
     * <code>.proto.Staff staff = 1;</code>
     * @return Whether the staff field is set.
     */
    @java.lang.Override
    public boolean hasStaff() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.proto.Staff staff = 1;</code>
     * @return The staff.
     */
    @java.lang.Override
    public generatedClasses.StaffOuterClass.Staff getStaff() {
      return staff_ == null ? generatedClasses.StaffOuterClass.Staff.getDefaultInstance() : staff_;
    }
    /**
     * <code>.proto.Staff staff = 1;</code>
     */
    @java.lang.Override
    public generatedClasses.StaffOuterClass.StaffOrBuilder getStaffOrBuilder() {
      return staff_ == null ? generatedClasses.StaffOuterClass.Staff.getDefaultInstance() : staff_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getStaff());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStaff());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generatedClasses.StaffRequestOuterClass.StaffRequest)) {
        return super.equals(obj);
      }
      generatedClasses.StaffRequestOuterClass.StaffRequest other = (generatedClasses.StaffRequestOuterClass.StaffRequest) obj;

      if (hasStaff() != other.hasStaff()) return false;
      if (hasStaff()) {
        if (!getStaff()
            .equals(other.getStaff())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStaff()) {
        hash = (37 * hash) + STAFF_FIELD_NUMBER;
        hash = (53 * hash) + getStaff().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffRequestOuterClass.StaffRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generatedClasses.StaffRequestOuterClass.StaffRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.StaffRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.StaffRequest)
        generatedClasses.StaffRequestOuterClass.StaffRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedClasses.StaffRequestOuterClass.StaffRequest.class, generatedClasses.StaffRequestOuterClass.StaffRequest.Builder.class);
      }

      // Construct using generatedClasses.StaffRequestOuterClass.StaffRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStaffFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        staff_ = null;
        if (staffBuilder_ != null) {
          staffBuilder_.dispose();
          staffBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedClasses.StaffRequestOuterClass.internal_static_proto_StaffRequest_descriptor;
      }

      @java.lang.Override
      public generatedClasses.StaffRequestOuterClass.StaffRequest getDefaultInstanceForType() {
        return generatedClasses.StaffRequestOuterClass.StaffRequest.getDefaultInstance();
      }

      @java.lang.Override
      public generatedClasses.StaffRequestOuterClass.StaffRequest build() {
        generatedClasses.StaffRequestOuterClass.StaffRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generatedClasses.StaffRequestOuterClass.StaffRequest buildPartial() {
        generatedClasses.StaffRequestOuterClass.StaffRequest result = new generatedClasses.StaffRequestOuterClass.StaffRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(generatedClasses.StaffRequestOuterClass.StaffRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.staff_ = staffBuilder_ == null
              ? staff_
              : staffBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedClasses.StaffRequestOuterClass.StaffRequest) {
          return mergeFrom((generatedClasses.StaffRequestOuterClass.StaffRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedClasses.StaffRequestOuterClass.StaffRequest other) {
        if (other == generatedClasses.StaffRequestOuterClass.StaffRequest.getDefaultInstance()) return this;
        if (other.hasStaff()) {
          mergeStaff(other.getStaff());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getStaffFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private generatedClasses.StaffOuterClass.Staff staff_;
      private com.google.protobuf.SingleFieldBuilderV3<
          generatedClasses.StaffOuterClass.Staff, generatedClasses.StaffOuterClass.Staff.Builder, generatedClasses.StaffOuterClass.StaffOrBuilder> staffBuilder_;
      /**
       * <code>.proto.Staff staff = 1;</code>
       * @return Whether the staff field is set.
       */
      public boolean hasStaff() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       * @return The staff.
       */
      public generatedClasses.StaffOuterClass.Staff getStaff() {
        if (staffBuilder_ == null) {
          return staff_ == null ? generatedClasses.StaffOuterClass.Staff.getDefaultInstance() : staff_;
        } else {
          return staffBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       */
      public Builder setStaff(generatedClasses.StaffOuterClass.Staff value) {
        if (staffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          staff_ = value;
        } else {
          staffBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       */
      public Builder setStaff(
          generatedClasses.StaffOuterClass.Staff.Builder builderForValue) {
        if (staffBuilder_ == null) {
          staff_ = builderForValue.build();
        } else {
          staffBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       */
      public Builder mergeStaff(generatedClasses.StaffOuterClass.Staff value) {
        if (staffBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            staff_ != null &&
            staff_ != generatedClasses.StaffOuterClass.Staff.getDefaultInstance()) {
            getStaffBuilder().mergeFrom(value);
          } else {
            staff_ = value;
          }
        } else {
          staffBuilder_.mergeFrom(value);
        }
        if (staff_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       */
      public Builder clearStaff() {
        bitField0_ = (bitField0_ & ~0x00000001);
        staff_ = null;
        if (staffBuilder_ != null) {
          staffBuilder_.dispose();
          staffBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       */
      public generatedClasses.StaffOuterClass.Staff.Builder getStaffBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStaffFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       */
      public generatedClasses.StaffOuterClass.StaffOrBuilder getStaffOrBuilder() {
        if (staffBuilder_ != null) {
          return staffBuilder_.getMessageOrBuilder();
        } else {
          return staff_ == null ?
              generatedClasses.StaffOuterClass.Staff.getDefaultInstance() : staff_;
        }
      }
      /**
       * <code>.proto.Staff staff = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          generatedClasses.StaffOuterClass.Staff, generatedClasses.StaffOuterClass.Staff.Builder, generatedClasses.StaffOuterClass.StaffOrBuilder> 
          getStaffFieldBuilder() {
        if (staffBuilder_ == null) {
          staffBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              generatedClasses.StaffOuterClass.Staff, generatedClasses.StaffOuterClass.Staff.Builder, generatedClasses.StaffOuterClass.StaffOrBuilder>(
                  getStaff(),
                  getParentForChildren(),
                  isClean());
          staff_ = null;
        }
        return staffBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.StaffRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.StaffRequest)
    private static final generatedClasses.StaffRequestOuterClass.StaffRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generatedClasses.StaffRequestOuterClass.StaffRequest();
    }

    public static generatedClasses.StaffRequestOuterClass.StaffRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StaffRequest>
        PARSER = new com.google.protobuf.AbstractParser<StaffRequest>() {
      @java.lang.Override
      public StaffRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StaffRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StaffRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generatedClasses.StaffRequestOuterClass.StaffRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StaffRequest1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StaffRequest1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StaffRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StaffRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StaffRequest.proto\022\005proto\032\013Staff.proto" +
      "\"!\n\rStaffRequest1\022\020\n\010staff_id\030\001 \001(\005\"+\n\014S" +
      "taffRequest\022\033\n\005staff\030\001 \001(\0132\014.proto.Staff" +
      "B\022\n\020generatedClassesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          generatedClasses.StaffOuterClass.getDescriptor(),
        });
    internal_static_proto_StaffRequest1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_StaffRequest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StaffRequest1_descriptor,
        new java.lang.String[] { "StaffId", });
    internal_static_proto_StaffRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_StaffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StaffRequest_descriptor,
        new java.lang.String[] { "Staff", });
    generatedClasses.StaffOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
