// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StaffListResponse.proto

// Protobuf Java Version: 3.25.1
package generatedClasses;

public final class StaffListResponseOuterClass {
  private StaffListResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StaffListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.StaffListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    java.util.List<generatedClasses.StaffOuterClass.Staff> 
        getStaffList();
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    generatedClasses.StaffOuterClass.Staff getStaff(int index);
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    int getStaffCount();
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    java.util.List<? extends generatedClasses.StaffOuterClass.StaffOrBuilder> 
        getStaffOrBuilderList();
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    generatedClasses.StaffOuterClass.StaffOrBuilder getStaffOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.StaffListResponse}
   */
  public static final class StaffListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.StaffListResponse)
      StaffListResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StaffListResponse.newBuilder() to construct.
    private StaffListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StaffListResponse() {
      staff_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StaffListResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedClasses.StaffListResponseOuterClass.internal_static_proto_StaffListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedClasses.StaffListResponseOuterClass.internal_static_proto_StaffListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedClasses.StaffListResponseOuterClass.StaffListResponse.class, generatedClasses.StaffListResponseOuterClass.StaffListResponse.Builder.class);
    }

    public static final int STAFF_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<generatedClasses.StaffOuterClass.Staff> staff_;
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    @java.lang.Override
    public java.util.List<generatedClasses.StaffOuterClass.Staff> getStaffList() {
      return staff_;
    }
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends generatedClasses.StaffOuterClass.StaffOrBuilder> 
        getStaffOrBuilderList() {
      return staff_;
    }
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    @java.lang.Override
    public int getStaffCount() {
      return staff_.size();
    }
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    @java.lang.Override
    public generatedClasses.StaffOuterClass.Staff getStaff(int index) {
      return staff_.get(index);
    }
    /**
     * <code>repeated .proto.Staff staff = 1;</code>
     */
    @java.lang.Override
    public generatedClasses.StaffOuterClass.StaffOrBuilder getStaffOrBuilder(
        int index) {
      return staff_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < staff_.size(); i++) {
        output.writeMessage(1, staff_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < staff_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, staff_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generatedClasses.StaffListResponseOuterClass.StaffListResponse)) {
        return super.equals(obj);
      }
      generatedClasses.StaffListResponseOuterClass.StaffListResponse other = (generatedClasses.StaffListResponseOuterClass.StaffListResponse) obj;

      if (!getStaffList()
          .equals(other.getStaffList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStaffCount() > 0) {
        hash = (37 * hash) + STAFF_FIELD_NUMBER;
        hash = (53 * hash) + getStaffList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generatedClasses.StaffListResponseOuterClass.StaffListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.StaffListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.StaffListResponse)
        generatedClasses.StaffListResponseOuterClass.StaffListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedClasses.StaffListResponseOuterClass.internal_static_proto_StaffListResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedClasses.StaffListResponseOuterClass.internal_static_proto_StaffListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedClasses.StaffListResponseOuterClass.StaffListResponse.class, generatedClasses.StaffListResponseOuterClass.StaffListResponse.Builder.class);
      }

      // Construct using generatedClasses.StaffListResponseOuterClass.StaffListResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (staffBuilder_ == null) {
          staff_ = java.util.Collections.emptyList();
        } else {
          staff_ = null;
          staffBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedClasses.StaffListResponseOuterClass.internal_static_proto_StaffListResponse_descriptor;
      }

      @java.lang.Override
      public generatedClasses.StaffListResponseOuterClass.StaffListResponse getDefaultInstanceForType() {
        return generatedClasses.StaffListResponseOuterClass.StaffListResponse.getDefaultInstance();
      }

      @java.lang.Override
      public generatedClasses.StaffListResponseOuterClass.StaffListResponse build() {
        generatedClasses.StaffListResponseOuterClass.StaffListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generatedClasses.StaffListResponseOuterClass.StaffListResponse buildPartial() {
        generatedClasses.StaffListResponseOuterClass.StaffListResponse result = new generatedClasses.StaffListResponseOuterClass.StaffListResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(generatedClasses.StaffListResponseOuterClass.StaffListResponse result) {
        if (staffBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            staff_ = java.util.Collections.unmodifiableList(staff_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.staff_ = staff_;
        } else {
          result.staff_ = staffBuilder_.build();
        }
      }

      private void buildPartial0(generatedClasses.StaffListResponseOuterClass.StaffListResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedClasses.StaffListResponseOuterClass.StaffListResponse) {
          return mergeFrom((generatedClasses.StaffListResponseOuterClass.StaffListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedClasses.StaffListResponseOuterClass.StaffListResponse other) {
        if (other == generatedClasses.StaffListResponseOuterClass.StaffListResponse.getDefaultInstance()) return this;
        if (staffBuilder_ == null) {
          if (!other.staff_.isEmpty()) {
            if (staff_.isEmpty()) {
              staff_ = other.staff_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStaffIsMutable();
              staff_.addAll(other.staff_);
            }
            onChanged();
          }
        } else {
          if (!other.staff_.isEmpty()) {
            if (staffBuilder_.isEmpty()) {
              staffBuilder_.dispose();
              staffBuilder_ = null;
              staff_ = other.staff_;
              bitField0_ = (bitField0_ & ~0x00000001);
              staffBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStaffFieldBuilder() : null;
            } else {
              staffBuilder_.addAllMessages(other.staff_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                generatedClasses.StaffOuterClass.Staff m =
                    input.readMessage(
                        generatedClasses.StaffOuterClass.Staff.parser(),
                        extensionRegistry);
                if (staffBuilder_ == null) {
                  ensureStaffIsMutable();
                  staff_.add(m);
                } else {
                  staffBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<generatedClasses.StaffOuterClass.Staff> staff_ =
        java.util.Collections.emptyList();
      private void ensureStaffIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          staff_ = new java.util.ArrayList<generatedClasses.StaffOuterClass.Staff>(staff_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          generatedClasses.StaffOuterClass.Staff, generatedClasses.StaffOuterClass.Staff.Builder, generatedClasses.StaffOuterClass.StaffOrBuilder> staffBuilder_;

      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public java.util.List<generatedClasses.StaffOuterClass.Staff> getStaffList() {
        if (staffBuilder_ == null) {
          return java.util.Collections.unmodifiableList(staff_);
        } else {
          return staffBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public int getStaffCount() {
        if (staffBuilder_ == null) {
          return staff_.size();
        } else {
          return staffBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public generatedClasses.StaffOuterClass.Staff getStaff(int index) {
        if (staffBuilder_ == null) {
          return staff_.get(index);
        } else {
          return staffBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder setStaff(
          int index, generatedClasses.StaffOuterClass.Staff value) {
        if (staffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStaffIsMutable();
          staff_.set(index, value);
          onChanged();
        } else {
          staffBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder setStaff(
          int index, generatedClasses.StaffOuterClass.Staff.Builder builderForValue) {
        if (staffBuilder_ == null) {
          ensureStaffIsMutable();
          staff_.set(index, builderForValue.build());
          onChanged();
        } else {
          staffBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder addStaff(generatedClasses.StaffOuterClass.Staff value) {
        if (staffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStaffIsMutable();
          staff_.add(value);
          onChanged();
        } else {
          staffBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder addStaff(
          int index, generatedClasses.StaffOuterClass.Staff value) {
        if (staffBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStaffIsMutable();
          staff_.add(index, value);
          onChanged();
        } else {
          staffBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder addStaff(
          generatedClasses.StaffOuterClass.Staff.Builder builderForValue) {
        if (staffBuilder_ == null) {
          ensureStaffIsMutable();
          staff_.add(builderForValue.build());
          onChanged();
        } else {
          staffBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder addStaff(
          int index, generatedClasses.StaffOuterClass.Staff.Builder builderForValue) {
        if (staffBuilder_ == null) {
          ensureStaffIsMutable();
          staff_.add(index, builderForValue.build());
          onChanged();
        } else {
          staffBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder addAllStaff(
          java.lang.Iterable<? extends generatedClasses.StaffOuterClass.Staff> values) {
        if (staffBuilder_ == null) {
          ensureStaffIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, staff_);
          onChanged();
        } else {
          staffBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder clearStaff() {
        if (staffBuilder_ == null) {
          staff_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          staffBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public Builder removeStaff(int index) {
        if (staffBuilder_ == null) {
          ensureStaffIsMutable();
          staff_.remove(index);
          onChanged();
        } else {
          staffBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public generatedClasses.StaffOuterClass.Staff.Builder getStaffBuilder(
          int index) {
        return getStaffFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public generatedClasses.StaffOuterClass.StaffOrBuilder getStaffOrBuilder(
          int index) {
        if (staffBuilder_ == null) {
          return staff_.get(index);  } else {
          return staffBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public java.util.List<? extends generatedClasses.StaffOuterClass.StaffOrBuilder> 
           getStaffOrBuilderList() {
        if (staffBuilder_ != null) {
          return staffBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(staff_);
        }
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public generatedClasses.StaffOuterClass.Staff.Builder addStaffBuilder() {
        return getStaffFieldBuilder().addBuilder(
            generatedClasses.StaffOuterClass.Staff.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public generatedClasses.StaffOuterClass.Staff.Builder addStaffBuilder(
          int index) {
        return getStaffFieldBuilder().addBuilder(
            index, generatedClasses.StaffOuterClass.Staff.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Staff staff = 1;</code>
       */
      public java.util.List<generatedClasses.StaffOuterClass.Staff.Builder> 
           getStaffBuilderList() {
        return getStaffFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          generatedClasses.StaffOuterClass.Staff, generatedClasses.StaffOuterClass.Staff.Builder, generatedClasses.StaffOuterClass.StaffOrBuilder> 
          getStaffFieldBuilder() {
        if (staffBuilder_ == null) {
          staffBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              generatedClasses.StaffOuterClass.Staff, generatedClasses.StaffOuterClass.Staff.Builder, generatedClasses.StaffOuterClass.StaffOrBuilder>(
                  staff_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          staff_ = null;
        }
        return staffBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.StaffListResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.StaffListResponse)
    private static final generatedClasses.StaffListResponseOuterClass.StaffListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generatedClasses.StaffListResponseOuterClass.StaffListResponse();
    }

    public static generatedClasses.StaffListResponseOuterClass.StaffListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StaffListResponse>
        PARSER = new com.google.protobuf.AbstractParser<StaffListResponse>() {
      @java.lang.Override
      public StaffListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StaffListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StaffListResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generatedClasses.StaffListResponseOuterClass.StaffListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StaffListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StaffListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027StaffListResponse.proto\022\005proto\032\013Staff." +
      "proto\"0\n\021StaffListResponse\022\033\n\005staff\030\001 \003(" +
      "\0132\014.proto.StaffB\022\n\020generatedClassesb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          generatedClasses.StaffOuterClass.getDescriptor(),
        });
    internal_static_proto_StaffListResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_StaffListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StaffListResponse_descriptor,
        new java.lang.String[] { "Staff", });
    generatedClasses.StaffOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
