// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StaffRpc.proto

package generatedClasses;

public final class StaffRpc {
  private StaffRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016StaffRpc.proto\022\005proto\032\022StaffRequest.pr" +
      "oto\032\023StaffResponse.proto\032\024StatusResponse" +
      ".proto\032\026StaffListRequest.proto\032\027StaffLis" +
      "tResponse.proto2\277\002\n\014StaffService\0225\n\010AddS" +
      "taff\022\023.proto.StaffRequest\032\024.proto.StaffR" +
      "esponse\022:\n\014GetStaffInfo\022\024.proto.StaffReq" +
      "uest1\032\024.proto.StaffResponse\022F\n\017GetAllSta" +
      "ffInfo\022\027.proto.StaffListRequest\032\030.proto." +
      "StaffListResponse0\001\0228\n\013UpdateStaff\022\023.pro" +
      "to.StaffRequest\032\024.proto.StaffResponse\022:\n" +
      "\013RemoveStaff\022\024.proto.StaffRequest1\032\025.pro" +
      "to.StatusResponseB\022\n\020generatedClassesb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          generatedClasses.StaffRequestOuterClass.getDescriptor(),
          generatedClasses.StaffResponseOuterClass.getDescriptor(),
          generatedClasses.StatusResponseOuterClass.getDescriptor(),
          generatedClasses.StaffListRequestOuterClass.getDescriptor(),
          generatedClasses.StaffListResponseOuterClass.getDescriptor(),
        });
    generatedClasses.StaffRequestOuterClass.getDescriptor();
    generatedClasses.StaffResponseOuterClass.getDescriptor();
    generatedClasses.StatusResponseOuterClass.getDescriptor();
    generatedClasses.StaffListRequestOuterClass.getDescriptor();
    generatedClasses.StaffListResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
