// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Staff.proto

package generatedClasses;

public final class StaffOuterClass {
  private StaffOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StaffOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Staff)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    int getStaffId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string personal_phone = 3;</code>
     * @return The personalPhone.
     */
    java.lang.String getPersonalPhone();
    /**
     * <code>string personal_phone = 3;</code>
     * @return The bytes for personalPhone.
     */
    com.google.protobuf.ByteString
        getPersonalPhoneBytes();

    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The emergencyContactNumber.
     */
    java.lang.String getEmergencyContactNumber();
    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The bytes for emergencyContactNumber.
     */
    com.google.protobuf.ByteString
        getEmergencyContactNumberBytes();

    /**
     * <code>string position = 5;</code>
     * @return The position.
     */
    java.lang.String getPosition();
    /**
     * <code>string position = 5;</code>
     * @return The bytes for position.
     */
    com.google.protobuf.ByteString
        getPositionBytes();

    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The citizenshipPhoto.
     */
    java.lang.String getCitizenshipPhoto();
    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The bytes for citizenshipPhoto.
     */
    com.google.protobuf.ByteString
        getCitizenshipPhotoBytes();

    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The contactDocPdf.
     */
    java.lang.String getContactDocPdf();
    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The bytes for contactDocPdf.
     */
    com.google.protobuf.ByteString
        getContactDocPdfBytes();

    /**
     * <code>string join_date = 8;</code>
     * @return The joinDate.
     */
    java.lang.String getJoinDate();
    /**
     * <code>string join_date = 8;</code>
     * @return The bytes for joinDate.
     */
    com.google.protobuf.ByteString
        getJoinDateBytes();

    /**
     * <code>string contact_renew_date = 9;</code>
     * @return The contactRenewDate.
     */
    java.lang.String getContactRenewDate();
    /**
     * <code>string contact_renew_date = 9;</code>
     * @return The bytes for contactRenewDate.
     */
    com.google.protobuf.ByteString
        getContactRenewDateBytes();
  }
  /**
   * Protobuf type {@code proto.Staff}
   */
  public static final class Staff extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Staff)
      StaffOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Staff.newBuilder() to construct.
    private Staff(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Staff() {
      name_ = "";
      personalPhone_ = "";
      emergencyContactNumber_ = "";
      position_ = "";
      citizenshipPhoto_ = "";
      contactDocPdf_ = "";
      joinDate_ = "";
      contactRenewDate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Staff();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Staff(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              staffId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              personalPhone_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              emergencyContactNumber_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              position_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              citizenshipPhoto_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              contactDocPdf_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              joinDate_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              contactRenewDate_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedClasses.StaffOuterClass.internal_static_proto_Staff_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedClasses.StaffOuterClass.internal_static_proto_Staff_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedClasses.StaffOuterClass.Staff.class, generatedClasses.StaffOuterClass.Staff.Builder.class);
    }

    public static final int STAFF_ID_FIELD_NUMBER = 1;
    private int staffId_;
    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    @java.lang.Override
    public int getStaffId() {
      return staffId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSONAL_PHONE_FIELD_NUMBER = 3;
    private volatile java.lang.Object personalPhone_;
    /**
     * <code>string personal_phone = 3;</code>
     * @return The personalPhone.
     */
    @java.lang.Override
    public java.lang.String getPersonalPhone() {
      java.lang.Object ref = personalPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personalPhone_ = s;
        return s;
      }
    }
    /**
     * <code>string personal_phone = 3;</code>
     * @return The bytes for personalPhone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPersonalPhoneBytes() {
      java.lang.Object ref = personalPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personalPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMERGENCY_CONTACT_NUMBER_FIELD_NUMBER = 4;
    private volatile java.lang.Object emergencyContactNumber_;
    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The emergencyContactNumber.
     */
    @java.lang.Override
    public java.lang.String getEmergencyContactNumber() {
      java.lang.Object ref = emergencyContactNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emergencyContactNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The bytes for emergencyContactNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmergencyContactNumberBytes() {
      java.lang.Object ref = emergencyContactNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emergencyContactNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 5;
    private volatile java.lang.Object position_;
    /**
     * <code>string position = 5;</code>
     * @return The position.
     */
    @java.lang.Override
    public java.lang.String getPosition() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        position_ = s;
        return s;
      }
    }
    /**
     * <code>string position = 5;</code>
     * @return The bytes for position.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPositionBytes() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        position_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITIZENSHIP_PHOTO_FIELD_NUMBER = 6;
    private volatile java.lang.Object citizenshipPhoto_;
    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The citizenshipPhoto.
     */
    @java.lang.Override
    public java.lang.String getCitizenshipPhoto() {
      java.lang.Object ref = citizenshipPhoto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        citizenshipPhoto_ = s;
        return s;
      }
    }
    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The bytes for citizenshipPhoto.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCitizenshipPhotoBytes() {
      java.lang.Object ref = citizenshipPhoto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        citizenshipPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACT_DOC_PDF_FIELD_NUMBER = 7;
    private volatile java.lang.Object contactDocPdf_;
    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The contactDocPdf.
     */
    @java.lang.Override
    public java.lang.String getContactDocPdf() {
      java.lang.Object ref = contactDocPdf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactDocPdf_ = s;
        return s;
      }
    }
    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The bytes for contactDocPdf.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContactDocPdfBytes() {
      java.lang.Object ref = contactDocPdf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactDocPdf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOIN_DATE_FIELD_NUMBER = 8;
    private volatile java.lang.Object joinDate_;
    /**
     * <code>string join_date = 8;</code>
     * @return The joinDate.
     */
    @java.lang.Override
    public java.lang.String getJoinDate() {
      java.lang.Object ref = joinDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        joinDate_ = s;
        return s;
      }
    }
    /**
     * <code>string join_date = 8;</code>
     * @return The bytes for joinDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJoinDateBytes() {
      java.lang.Object ref = joinDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        joinDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACT_RENEW_DATE_FIELD_NUMBER = 9;
    private volatile java.lang.Object contactRenewDate_;
    /**
     * <code>string contact_renew_date = 9;</code>
     * @return The contactRenewDate.
     */
    @java.lang.Override
    public java.lang.String getContactRenewDate() {
      java.lang.Object ref = contactRenewDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactRenewDate_ = s;
        return s;
      }
    }
    /**
     * <code>string contact_renew_date = 9;</code>
     * @return The bytes for contactRenewDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContactRenewDateBytes() {
      java.lang.Object ref = contactRenewDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactRenewDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (staffId_ != 0) {
        output.writeInt32(1, staffId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getPersonalPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, personalPhone_);
      }
      if (!getEmergencyContactNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, emergencyContactNumber_);
      }
      if (!getPositionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, position_);
      }
      if (!getCitizenshipPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, citizenshipPhoto_);
      }
      if (!getContactDocPdfBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, contactDocPdf_);
      }
      if (!getJoinDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, joinDate_);
      }
      if (!getContactRenewDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, contactRenewDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (staffId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, staffId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getPersonalPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, personalPhone_);
      }
      if (!getEmergencyContactNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, emergencyContactNumber_);
      }
      if (!getPositionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, position_);
      }
      if (!getCitizenshipPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, citizenshipPhoto_);
      }
      if (!getContactDocPdfBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, contactDocPdf_);
      }
      if (!getJoinDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, joinDate_);
      }
      if (!getContactRenewDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, contactRenewDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generatedClasses.StaffOuterClass.Staff)) {
        return super.equals(obj);
      }
      generatedClasses.StaffOuterClass.Staff other = (generatedClasses.StaffOuterClass.Staff) obj;

      if (getStaffId()
          != other.getStaffId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPersonalPhone()
          .equals(other.getPersonalPhone())) return false;
      if (!getEmergencyContactNumber()
          .equals(other.getEmergencyContactNumber())) return false;
      if (!getPosition()
          .equals(other.getPosition())) return false;
      if (!getCitizenshipPhoto()
          .equals(other.getCitizenshipPhoto())) return false;
      if (!getContactDocPdf()
          .equals(other.getContactDocPdf())) return false;
      if (!getJoinDate()
          .equals(other.getJoinDate())) return false;
      if (!getContactRenewDate()
          .equals(other.getContactRenewDate())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STAFF_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStaffId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PERSONAL_PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPersonalPhone().hashCode();
      hash = (37 * hash) + EMERGENCY_CONTACT_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getEmergencyContactNumber().hashCode();
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
      hash = (37 * hash) + CITIZENSHIP_PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getCitizenshipPhoto().hashCode();
      hash = (37 * hash) + CONTACT_DOC_PDF_FIELD_NUMBER;
      hash = (53 * hash) + getContactDocPdf().hashCode();
      hash = (37 * hash) + JOIN_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getJoinDate().hashCode();
      hash = (37 * hash) + CONTACT_RENEW_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getContactRenewDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.StaffOuterClass.Staff parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffOuterClass.Staff parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffOuterClass.Staff parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generatedClasses.StaffOuterClass.Staff prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Staff}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Staff)
        generatedClasses.StaffOuterClass.StaffOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedClasses.StaffOuterClass.internal_static_proto_Staff_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedClasses.StaffOuterClass.internal_static_proto_Staff_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedClasses.StaffOuterClass.Staff.class, generatedClasses.StaffOuterClass.Staff.Builder.class);
      }

      // Construct using generatedClasses.StaffOuterClass.Staff.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        staffId_ = 0;

        name_ = "";

        personalPhone_ = "";

        emergencyContactNumber_ = "";

        position_ = "";

        citizenshipPhoto_ = "";

        contactDocPdf_ = "";

        joinDate_ = "";

        contactRenewDate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedClasses.StaffOuterClass.internal_static_proto_Staff_descriptor;
      }

      @java.lang.Override
      public generatedClasses.StaffOuterClass.Staff getDefaultInstanceForType() {
        return generatedClasses.StaffOuterClass.Staff.getDefaultInstance();
      }

      @java.lang.Override
      public generatedClasses.StaffOuterClass.Staff build() {
        generatedClasses.StaffOuterClass.Staff result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generatedClasses.StaffOuterClass.Staff buildPartial() {
        generatedClasses.StaffOuterClass.Staff result = new generatedClasses.StaffOuterClass.Staff(this);
        result.staffId_ = staffId_;
        result.name_ = name_;
        result.personalPhone_ = personalPhone_;
        result.emergencyContactNumber_ = emergencyContactNumber_;
        result.position_ = position_;
        result.citizenshipPhoto_ = citizenshipPhoto_;
        result.contactDocPdf_ = contactDocPdf_;
        result.joinDate_ = joinDate_;
        result.contactRenewDate_ = contactRenewDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedClasses.StaffOuterClass.Staff) {
          return mergeFrom((generatedClasses.StaffOuterClass.Staff)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedClasses.StaffOuterClass.Staff other) {
        if (other == generatedClasses.StaffOuterClass.Staff.getDefaultInstance()) return this;
        if (other.getStaffId() != 0) {
          setStaffId(other.getStaffId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPersonalPhone().isEmpty()) {
          personalPhone_ = other.personalPhone_;
          onChanged();
        }
        if (!other.getEmergencyContactNumber().isEmpty()) {
          emergencyContactNumber_ = other.emergencyContactNumber_;
          onChanged();
        }
        if (!other.getPosition().isEmpty()) {
          position_ = other.position_;
          onChanged();
        }
        if (!other.getCitizenshipPhoto().isEmpty()) {
          citizenshipPhoto_ = other.citizenshipPhoto_;
          onChanged();
        }
        if (!other.getContactDocPdf().isEmpty()) {
          contactDocPdf_ = other.contactDocPdf_;
          onChanged();
        }
        if (!other.getJoinDate().isEmpty()) {
          joinDate_ = other.joinDate_;
          onChanged();
        }
        if (!other.getContactRenewDate().isEmpty()) {
          contactRenewDate_ = other.contactRenewDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        generatedClasses.StaffOuterClass.Staff parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (generatedClasses.StaffOuterClass.Staff) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int staffId_ ;
      /**
       * <code>int32 staff_id = 1;</code>
       * @return The staffId.
       */
      @java.lang.Override
      public int getStaffId() {
        return staffId_;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @param value The staffId to set.
       * @return This builder for chaining.
       */
      public Builder setStaffId(int value) {
        
        staffId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStaffId() {
        
        staffId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object personalPhone_ = "";
      /**
       * <code>string personal_phone = 3;</code>
       * @return The personalPhone.
       */
      public java.lang.String getPersonalPhone() {
        java.lang.Object ref = personalPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personalPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @return The bytes for personalPhone.
       */
      public com.google.protobuf.ByteString
          getPersonalPhoneBytes() {
        java.lang.Object ref = personalPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personalPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @param value The personalPhone to set.
       * @return This builder for chaining.
       */
      public Builder setPersonalPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        personalPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPersonalPhone() {
        
        personalPhone_ = getDefaultInstance().getPersonalPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @param value The bytes for personalPhone to set.
       * @return This builder for chaining.
       */
      public Builder setPersonalPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        personalPhone_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object emergencyContactNumber_ = "";
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @return The emergencyContactNumber.
       */
      public java.lang.String getEmergencyContactNumber() {
        java.lang.Object ref = emergencyContactNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emergencyContactNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @return The bytes for emergencyContactNumber.
       */
      public com.google.protobuf.ByteString
          getEmergencyContactNumberBytes() {
        java.lang.Object ref = emergencyContactNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emergencyContactNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @param value The emergencyContactNumber to set.
       * @return This builder for chaining.
       */
      public Builder setEmergencyContactNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        emergencyContactNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmergencyContactNumber() {
        
        emergencyContactNumber_ = getDefaultInstance().getEmergencyContactNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @param value The bytes for emergencyContactNumber to set.
       * @return This builder for chaining.
       */
      public Builder setEmergencyContactNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        emergencyContactNumber_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object position_ = "";
      /**
       * <code>string position = 5;</code>
       * @return The position.
       */
      public java.lang.String getPosition() {
        java.lang.Object ref = position_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          position_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string position = 5;</code>
       * @return The bytes for position.
       */
      public com.google.protobuf.ByteString
          getPositionBytes() {
        java.lang.Object ref = position_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          position_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string position = 5;</code>
       * @param value The position to set.
       * @return This builder for chaining.
       */
      public Builder setPosition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        position_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string position = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosition() {
        
        position_ = getDefaultInstance().getPosition();
        onChanged();
        return this;
      }
      /**
       * <code>string position = 5;</code>
       * @param value The bytes for position to set.
       * @return This builder for chaining.
       */
      public Builder setPositionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        position_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object citizenshipPhoto_ = "";
      /**
       * <code>string citizenship_photo = 6;</code>
       * @return The citizenshipPhoto.
       */
      public java.lang.String getCitizenshipPhoto() {
        java.lang.Object ref = citizenshipPhoto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          citizenshipPhoto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @return The bytes for citizenshipPhoto.
       */
      public com.google.protobuf.ByteString
          getCitizenshipPhotoBytes() {
        java.lang.Object ref = citizenshipPhoto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          citizenshipPhoto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @param value The citizenshipPhoto to set.
       * @return This builder for chaining.
       */
      public Builder setCitizenshipPhoto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        citizenshipPhoto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCitizenshipPhoto() {
        
        citizenshipPhoto_ = getDefaultInstance().getCitizenshipPhoto();
        onChanged();
        return this;
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @param value The bytes for citizenshipPhoto to set.
       * @return This builder for chaining.
       */
      public Builder setCitizenshipPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        citizenshipPhoto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contactDocPdf_ = "";
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @return The contactDocPdf.
       */
      public java.lang.String getContactDocPdf() {
        java.lang.Object ref = contactDocPdf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contactDocPdf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @return The bytes for contactDocPdf.
       */
      public com.google.protobuf.ByteString
          getContactDocPdfBytes() {
        java.lang.Object ref = contactDocPdf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactDocPdf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @param value The contactDocPdf to set.
       * @return This builder for chaining.
       */
      public Builder setContactDocPdf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contactDocPdf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContactDocPdf() {
        
        contactDocPdf_ = getDefaultInstance().getContactDocPdf();
        onChanged();
        return this;
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @param value The bytes for contactDocPdf to set.
       * @return This builder for chaining.
       */
      public Builder setContactDocPdfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contactDocPdf_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object joinDate_ = "";
      /**
       * <code>string join_date = 8;</code>
       * @return The joinDate.
       */
      public java.lang.String getJoinDate() {
        java.lang.Object ref = joinDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          joinDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string join_date = 8;</code>
       * @return The bytes for joinDate.
       */
      public com.google.protobuf.ByteString
          getJoinDateBytes() {
        java.lang.Object ref = joinDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          joinDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string join_date = 8;</code>
       * @param value The joinDate to set.
       * @return This builder for chaining.
       */
      public Builder setJoinDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        joinDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string join_date = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearJoinDate() {
        
        joinDate_ = getDefaultInstance().getJoinDate();
        onChanged();
        return this;
      }
      /**
       * <code>string join_date = 8;</code>
       * @param value The bytes for joinDate to set.
       * @return This builder for chaining.
       */
      public Builder setJoinDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        joinDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contactRenewDate_ = "";
      /**
       * <code>string contact_renew_date = 9;</code>
       * @return The contactRenewDate.
       */
      public java.lang.String getContactRenewDate() {
        java.lang.Object ref = contactRenewDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contactRenewDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contact_renew_date = 9;</code>
       * @return The bytes for contactRenewDate.
       */
      public com.google.protobuf.ByteString
          getContactRenewDateBytes() {
        java.lang.Object ref = contactRenewDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactRenewDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contact_renew_date = 9;</code>
       * @param value The contactRenewDate to set.
       * @return This builder for chaining.
       */
      public Builder setContactRenewDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contactRenewDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string contact_renew_date = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearContactRenewDate() {
        
        contactRenewDate_ = getDefaultInstance().getContactRenewDate();
        onChanged();
        return this;
      }
      /**
       * <code>string contact_renew_date = 9;</code>
       * @param value The bytes for contactRenewDate to set.
       * @return This builder for chaining.
       */
      public Builder setContactRenewDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contactRenewDate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Staff)
    }

    // @@protoc_insertion_point(class_scope:proto.Staff)
    private static final generatedClasses.StaffOuterClass.Staff DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generatedClasses.StaffOuterClass.Staff();
    }

    public static generatedClasses.StaffOuterClass.Staff getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Staff>
        PARSER = new com.google.protobuf.AbstractParser<Staff>() {
      @java.lang.Override
      public Staff parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Staff(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Staff> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Staff> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generatedClasses.StaffOuterClass.Staff getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Staff_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Staff_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Staff.proto\022\005proto\"\326\001\n\005Staff\022\020\n\010staff_" +
      "id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\026\n\016personal_phone" +
      "\030\003 \001(\t\022 \n\030emergency_contact_number\030\004 \001(\t" +
      "\022\020\n\010position\030\005 \001(\t\022\031\n\021citizenship_photo\030" +
      "\006 \001(\t\022\027\n\017contact_doc_pdf\030\007 \001(\t\022\021\n\tjoin_d" +
      "ate\030\010 \001(\t\022\032\n\022contact_renew_date\030\t \001(\tB\022\n" +
      "\020generatedClassesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Staff_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Staff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Staff_descriptor,
        new java.lang.String[] { "StaffId", "Name", "PersonalPhone", "EmergencyContactNumber", "Position", "CitizenshipPhoto", "ContactDocPdf", "JoinDate", "ContactRenewDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
