// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StaffResponse.proto

// Protobuf Java Version: 3.25.1
package generatedClasses;

public final class StaffResponseOuterClass {
  private StaffResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StaffResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.StaffResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    int getStaffId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string personal_phone = 3;</code>
     * @return The personalPhone.
     */
    java.lang.String getPersonalPhone();
    /**
     * <code>string personal_phone = 3;</code>
     * @return The bytes for personalPhone.
     */
    com.google.protobuf.ByteString
        getPersonalPhoneBytes();

    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The emergencyContactNumber.
     */
    java.lang.String getEmergencyContactNumber();
    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The bytes for emergencyContactNumber.
     */
    com.google.protobuf.ByteString
        getEmergencyContactNumberBytes();

    /**
     * <code>string position = 5;</code>
     * @return The position.
     */
    java.lang.String getPosition();
    /**
     * <code>string position = 5;</code>
     * @return The bytes for position.
     */
    com.google.protobuf.ByteString
        getPositionBytes();

    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The citizenshipPhoto.
     */
    java.lang.String getCitizenshipPhoto();
    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The bytes for citizenshipPhoto.
     */
    com.google.protobuf.ByteString
        getCitizenshipPhotoBytes();

    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The contactDocPdf.
     */
    java.lang.String getContactDocPdf();
    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The bytes for contactDocPdf.
     */
    com.google.protobuf.ByteString
        getContactDocPdfBytes();

    /**
     * <code>int64 join_date = 8;</code>
     * @return The joinDate.
     */
    long getJoinDate();

    /**
     * <code>int64 contact_renew_date = 9;</code>
     * @return The contactRenewDate.
     */
    long getContactRenewDate();
  }
  /**
   * Protobuf type {@code proto.StaffResponse}
   */
  public static final class StaffResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.StaffResponse)
      StaffResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StaffResponse.newBuilder() to construct.
    private StaffResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StaffResponse() {
      name_ = "";
      personalPhone_ = "";
      emergencyContactNumber_ = "";
      position_ = "";
      citizenshipPhoto_ = "";
      contactDocPdf_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StaffResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return generatedClasses.StaffResponseOuterClass.internal_static_proto_StaffResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return generatedClasses.StaffResponseOuterClass.internal_static_proto_StaffResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              generatedClasses.StaffResponseOuterClass.StaffResponse.class, generatedClasses.StaffResponseOuterClass.StaffResponse.Builder.class);
    }

    public static final int STAFF_ID_FIELD_NUMBER = 1;
    private int staffId_ = 0;
    /**
     * <code>int32 staff_id = 1;</code>
     * @return The staffId.
     */
    @java.lang.Override
    public int getStaffId() {
      return staffId_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSONAL_PHONE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object personalPhone_ = "";
    /**
     * <code>string personal_phone = 3;</code>
     * @return The personalPhone.
     */
    @java.lang.Override
    public java.lang.String getPersonalPhone() {
      java.lang.Object ref = personalPhone_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        personalPhone_ = s;
        return s;
      }
    }
    /**
     * <code>string personal_phone = 3;</code>
     * @return The bytes for personalPhone.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPersonalPhoneBytes() {
      java.lang.Object ref = personalPhone_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        personalPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMERGENCY_CONTACT_NUMBER_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object emergencyContactNumber_ = "";
    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The emergencyContactNumber.
     */
    @java.lang.Override
    public java.lang.String getEmergencyContactNumber() {
      java.lang.Object ref = emergencyContactNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        emergencyContactNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string emergency_contact_number = 4;</code>
     * @return The bytes for emergencyContactNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmergencyContactNumberBytes() {
      java.lang.Object ref = emergencyContactNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        emergencyContactNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object position_ = "";
    /**
     * <code>string position = 5;</code>
     * @return The position.
     */
    @java.lang.Override
    public java.lang.String getPosition() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        position_ = s;
        return s;
      }
    }
    /**
     * <code>string position = 5;</code>
     * @return The bytes for position.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPositionBytes() {
      java.lang.Object ref = position_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        position_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITIZENSHIP_PHOTO_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object citizenshipPhoto_ = "";
    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The citizenshipPhoto.
     */
    @java.lang.Override
    public java.lang.String getCitizenshipPhoto() {
      java.lang.Object ref = citizenshipPhoto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        citizenshipPhoto_ = s;
        return s;
      }
    }
    /**
     * <code>string citizenship_photo = 6;</code>
     * @return The bytes for citizenshipPhoto.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCitizenshipPhotoBytes() {
      java.lang.Object ref = citizenshipPhoto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        citizenshipPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACT_DOC_PDF_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contactDocPdf_ = "";
    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The contactDocPdf.
     */
    @java.lang.Override
    public java.lang.String getContactDocPdf() {
      java.lang.Object ref = contactDocPdf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactDocPdf_ = s;
        return s;
      }
    }
    /**
     * <code>string contact_doc_pdf = 7;</code>
     * @return The bytes for contactDocPdf.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContactDocPdfBytes() {
      java.lang.Object ref = contactDocPdf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactDocPdf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOIN_DATE_FIELD_NUMBER = 8;
    private long joinDate_ = 0L;
    /**
     * <code>int64 join_date = 8;</code>
     * @return The joinDate.
     */
    @java.lang.Override
    public long getJoinDate() {
      return joinDate_;
    }

    public static final int CONTACT_RENEW_DATE_FIELD_NUMBER = 9;
    private long contactRenewDate_ = 0L;
    /**
     * <code>int64 contact_renew_date = 9;</code>
     * @return The contactRenewDate.
     */
    @java.lang.Override
    public long getContactRenewDate() {
      return contactRenewDate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (staffId_ != 0) {
        output.writeInt32(1, staffId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(personalPhone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, personalPhone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emergencyContactNumber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, emergencyContactNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(position_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, position_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(citizenshipPhoto_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, citizenshipPhoto_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contactDocPdf_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, contactDocPdf_);
      }
      if (joinDate_ != 0L) {
        output.writeInt64(8, joinDate_);
      }
      if (contactRenewDate_ != 0L) {
        output.writeInt64(9, contactRenewDate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (staffId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, staffId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(personalPhone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, personalPhone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(emergencyContactNumber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, emergencyContactNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(position_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, position_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(citizenshipPhoto_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, citizenshipPhoto_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contactDocPdf_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, contactDocPdf_);
      }
      if (joinDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, joinDate_);
      }
      if (contactRenewDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, contactRenewDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof generatedClasses.StaffResponseOuterClass.StaffResponse)) {
        return super.equals(obj);
      }
      generatedClasses.StaffResponseOuterClass.StaffResponse other = (generatedClasses.StaffResponseOuterClass.StaffResponse) obj;

      if (getStaffId()
          != other.getStaffId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getPersonalPhone()
          .equals(other.getPersonalPhone())) return false;
      if (!getEmergencyContactNumber()
          .equals(other.getEmergencyContactNumber())) return false;
      if (!getPosition()
          .equals(other.getPosition())) return false;
      if (!getCitizenshipPhoto()
          .equals(other.getCitizenshipPhoto())) return false;
      if (!getContactDocPdf()
          .equals(other.getContactDocPdf())) return false;
      if (getJoinDate()
          != other.getJoinDate()) return false;
      if (getContactRenewDate()
          != other.getContactRenewDate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STAFF_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStaffId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PERSONAL_PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPersonalPhone().hashCode();
      hash = (37 * hash) + EMERGENCY_CONTACT_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getEmergencyContactNumber().hashCode();
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
      hash = (37 * hash) + CITIZENSHIP_PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getCitizenshipPhoto().hashCode();
      hash = (37 * hash) + CONTACT_DOC_PDF_FIELD_NUMBER;
      hash = (53 * hash) + getContactDocPdf().hashCode();
      hash = (37 * hash) + JOIN_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getJoinDate());
      hash = (37 * hash) + CONTACT_RENEW_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getContactRenewDate());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static generatedClasses.StaffResponseOuterClass.StaffResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(generatedClasses.StaffResponseOuterClass.StaffResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.StaffResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.StaffResponse)
        generatedClasses.StaffResponseOuterClass.StaffResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return generatedClasses.StaffResponseOuterClass.internal_static_proto_StaffResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return generatedClasses.StaffResponseOuterClass.internal_static_proto_StaffResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                generatedClasses.StaffResponseOuterClass.StaffResponse.class, generatedClasses.StaffResponseOuterClass.StaffResponse.Builder.class);
      }

      // Construct using generatedClasses.StaffResponseOuterClass.StaffResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        staffId_ = 0;
        name_ = "";
        personalPhone_ = "";
        emergencyContactNumber_ = "";
        position_ = "";
        citizenshipPhoto_ = "";
        contactDocPdf_ = "";
        joinDate_ = 0L;
        contactRenewDate_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return generatedClasses.StaffResponseOuterClass.internal_static_proto_StaffResponse_descriptor;
      }

      @java.lang.Override
      public generatedClasses.StaffResponseOuterClass.StaffResponse getDefaultInstanceForType() {
        return generatedClasses.StaffResponseOuterClass.StaffResponse.getDefaultInstance();
      }

      @java.lang.Override
      public generatedClasses.StaffResponseOuterClass.StaffResponse build() {
        generatedClasses.StaffResponseOuterClass.StaffResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public generatedClasses.StaffResponseOuterClass.StaffResponse buildPartial() {
        generatedClasses.StaffResponseOuterClass.StaffResponse result = new generatedClasses.StaffResponseOuterClass.StaffResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(generatedClasses.StaffResponseOuterClass.StaffResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.staffId_ = staffId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.personalPhone_ = personalPhone_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.emergencyContactNumber_ = emergencyContactNumber_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.position_ = position_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.citizenshipPhoto_ = citizenshipPhoto_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.contactDocPdf_ = contactDocPdf_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.joinDate_ = joinDate_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.contactRenewDate_ = contactRenewDate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof generatedClasses.StaffResponseOuterClass.StaffResponse) {
          return mergeFrom((generatedClasses.StaffResponseOuterClass.StaffResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(generatedClasses.StaffResponseOuterClass.StaffResponse other) {
        if (other == generatedClasses.StaffResponseOuterClass.StaffResponse.getDefaultInstance()) return this;
        if (other.getStaffId() != 0) {
          setStaffId(other.getStaffId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getPersonalPhone().isEmpty()) {
          personalPhone_ = other.personalPhone_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getEmergencyContactNumber().isEmpty()) {
          emergencyContactNumber_ = other.emergencyContactNumber_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getPosition().isEmpty()) {
          position_ = other.position_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getCitizenshipPhoto().isEmpty()) {
          citizenshipPhoto_ = other.citizenshipPhoto_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getContactDocPdf().isEmpty()) {
          contactDocPdf_ = other.contactDocPdf_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getJoinDate() != 0L) {
          setJoinDate(other.getJoinDate());
        }
        if (other.getContactRenewDate() != 0L) {
          setContactRenewDate(other.getContactRenewDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                staffId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                personalPhone_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                emergencyContactNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                position_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                citizenshipPhoto_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                contactDocPdf_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                joinDate_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                contactRenewDate_ = input.readInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int staffId_ ;
      /**
       * <code>int32 staff_id = 1;</code>
       * @return The staffId.
       */
      @java.lang.Override
      public int getStaffId() {
        return staffId_;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @param value The staffId to set.
       * @return This builder for chaining.
       */
      public Builder setStaffId(int value) {

        staffId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 staff_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStaffId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        staffId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object personalPhone_ = "";
      /**
       * <code>string personal_phone = 3;</code>
       * @return The personalPhone.
       */
      public java.lang.String getPersonalPhone() {
        java.lang.Object ref = personalPhone_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          personalPhone_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @return The bytes for personalPhone.
       */
      public com.google.protobuf.ByteString
          getPersonalPhoneBytes() {
        java.lang.Object ref = personalPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          personalPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @param value The personalPhone to set.
       * @return This builder for chaining.
       */
      public Builder setPersonalPhone(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        personalPhone_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPersonalPhone() {
        personalPhone_ = getDefaultInstance().getPersonalPhone();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string personal_phone = 3;</code>
       * @param value The bytes for personalPhone to set.
       * @return This builder for chaining.
       */
      public Builder setPersonalPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        personalPhone_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object emergencyContactNumber_ = "";
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @return The emergencyContactNumber.
       */
      public java.lang.String getEmergencyContactNumber() {
        java.lang.Object ref = emergencyContactNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          emergencyContactNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @return The bytes for emergencyContactNumber.
       */
      public com.google.protobuf.ByteString
          getEmergencyContactNumberBytes() {
        java.lang.Object ref = emergencyContactNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          emergencyContactNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @param value The emergencyContactNumber to set.
       * @return This builder for chaining.
       */
      public Builder setEmergencyContactNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        emergencyContactNumber_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmergencyContactNumber() {
        emergencyContactNumber_ = getDefaultInstance().getEmergencyContactNumber();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string emergency_contact_number = 4;</code>
       * @param value The bytes for emergencyContactNumber to set.
       * @return This builder for chaining.
       */
      public Builder setEmergencyContactNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        emergencyContactNumber_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object position_ = "";
      /**
       * <code>string position = 5;</code>
       * @return The position.
       */
      public java.lang.String getPosition() {
        java.lang.Object ref = position_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          position_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string position = 5;</code>
       * @return The bytes for position.
       */
      public com.google.protobuf.ByteString
          getPositionBytes() {
        java.lang.Object ref = position_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          position_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string position = 5;</code>
       * @param value The position to set.
       * @return This builder for chaining.
       */
      public Builder setPosition(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        position_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string position = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosition() {
        position_ = getDefaultInstance().getPosition();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string position = 5;</code>
       * @param value The bytes for position to set.
       * @return This builder for chaining.
       */
      public Builder setPositionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        position_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object citizenshipPhoto_ = "";
      /**
       * <code>string citizenship_photo = 6;</code>
       * @return The citizenshipPhoto.
       */
      public java.lang.String getCitizenshipPhoto() {
        java.lang.Object ref = citizenshipPhoto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          citizenshipPhoto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @return The bytes for citizenshipPhoto.
       */
      public com.google.protobuf.ByteString
          getCitizenshipPhotoBytes() {
        java.lang.Object ref = citizenshipPhoto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          citizenshipPhoto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @param value The citizenshipPhoto to set.
       * @return This builder for chaining.
       */
      public Builder setCitizenshipPhoto(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        citizenshipPhoto_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCitizenshipPhoto() {
        citizenshipPhoto_ = getDefaultInstance().getCitizenshipPhoto();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string citizenship_photo = 6;</code>
       * @param value The bytes for citizenshipPhoto to set.
       * @return This builder for chaining.
       */
      public Builder setCitizenshipPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        citizenshipPhoto_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object contactDocPdf_ = "";
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @return The contactDocPdf.
       */
      public java.lang.String getContactDocPdf() {
        java.lang.Object ref = contactDocPdf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contactDocPdf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @return The bytes for contactDocPdf.
       */
      public com.google.protobuf.ByteString
          getContactDocPdfBytes() {
        java.lang.Object ref = contactDocPdf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactDocPdf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @param value The contactDocPdf to set.
       * @return This builder for chaining.
       */
      public Builder setContactDocPdf(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contactDocPdf_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearContactDocPdf() {
        contactDocPdf_ = getDefaultInstance().getContactDocPdf();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string contact_doc_pdf = 7;</code>
       * @param value The bytes for contactDocPdf to set.
       * @return This builder for chaining.
       */
      public Builder setContactDocPdfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contactDocPdf_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private long joinDate_ ;
      /**
       * <code>int64 join_date = 8;</code>
       * @return The joinDate.
       */
      @java.lang.Override
      public long getJoinDate() {
        return joinDate_;
      }
      /**
       * <code>int64 join_date = 8;</code>
       * @param value The joinDate to set.
       * @return This builder for chaining.
       */
      public Builder setJoinDate(long value) {

        joinDate_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 join_date = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearJoinDate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        joinDate_ = 0L;
        onChanged();
        return this;
      }

      private long contactRenewDate_ ;
      /**
       * <code>int64 contact_renew_date = 9;</code>
       * @return The contactRenewDate.
       */
      @java.lang.Override
      public long getContactRenewDate() {
        return contactRenewDate_;
      }
      /**
       * <code>int64 contact_renew_date = 9;</code>
       * @param value The contactRenewDate to set.
       * @return This builder for chaining.
       */
      public Builder setContactRenewDate(long value) {

        contactRenewDate_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int64 contact_renew_date = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearContactRenewDate() {
        bitField0_ = (bitField0_ & ~0x00000100);
        contactRenewDate_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.StaffResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.StaffResponse)
    private static final generatedClasses.StaffResponseOuterClass.StaffResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new generatedClasses.StaffResponseOuterClass.StaffResponse();
    }

    public static generatedClasses.StaffResponseOuterClass.StaffResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StaffResponse>
        PARSER = new com.google.protobuf.AbstractParser<StaffResponse>() {
      @java.lang.Override
      public StaffResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StaffResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StaffResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public generatedClasses.StaffResponseOuterClass.StaffResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StaffResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StaffResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023StaffResponse.proto\022\005proto\"\336\001\n\rStaffRe" +
      "sponse\022\020\n\010staff_id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\026" +
      "\n\016personal_phone\030\003 \001(\t\022 \n\030emergency_cont" +
      "act_number\030\004 \001(\t\022\020\n\010position\030\005 \001(\t\022\031\n\021ci" +
      "tizenship_photo\030\006 \001(\t\022\027\n\017contact_doc_pdf" +
      "\030\007 \001(\t\022\021\n\tjoin_date\030\010 \001(\003\022\032\n\022contact_ren" +
      "ew_date\030\t \001(\003B\022\n\020generatedClassesb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_StaffResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_StaffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StaffResponse_descriptor,
        new java.lang.String[] { "StaffId", "Name", "PersonalPhone", "EmergencyContactNumber", "Position", "CitizenshipPhoto", "ContactDocPdf", "JoinDate", "ContactRenewDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
